export const data = {
  Alajuela: {
    municipalities: [
      "San Carlos",
      "Zarcero",
      "Sarchí",
      "Upala",
      "Los Chiles",
      "Guatuso",
      "Río Cuarto",
      "Central",
      "San Ramón",
      "Grecia",
      "San Mateo",
      "Atenas",
      "Naranjo",
      "Palmares",
      "Poás",
      "Orotina",
    ],
  },
  Cartago: {
    municipalities: [
      "Central",
      "Paraíso",
      "La Unión",
      "Jiménez",
      "Turrialba",
      "Alvarado",
      "Oreamuno",
      "El Guarco",
    ],
  },
  Guanacaste: {
    municipalities: [
      "La Cruz",
      "Hojancha",
      "Liberia",
      "Nicoya",
      "Santa Cruz",
      "Bagaces",
      "Carrillo",
      "Cañas",
      "Abangares",
      "Tilarán",
      "Nandayure",
    ],
  },
  Heredia: {
    municipalities: [
      "Sarapiquí",
      "Central",
      "Barva",
      "Santo Domingo",
      "Santa Barbara",
      "San Rafael",
      "San Isidro",
      "Belén",
      "Flores",
      "San Pablo",
    ],
  },
  ["Limón"]: {
    municipalities: [
      "Central",
      "Pococí",
      "Siquirres",
      "Talamanca",
      "Matina",
      "Guácimo",
    ],
  },
  Puntarenas: {
    municipalities: [
      "Corredores",
      "Garabito",
      "Central",
      "Esparza",
      "Buenos Aires",
      "Montes De Oro",
      "Monte Verde",
      "Osa",
      "Quepos",
      "Golfito",
      "Coto Brus",
      "Parrita",
      "Puerto Jiménez",
    ],
  },
  ["San José"]: {
    municipalities: [
      "Alajuelita",
      "Vázquez De Coronado",
      "Acosta",
      "Tibás",
      "Moravia",
      "Montes De Oca",
      "Turrubares",
      "Dota",
      "Curridabat",
      "Pérez Zeledón",
      "León Cortés Castro",
      "Central",
      "Escazú",
      "Desamparados",
      "Puriscal",
      "Tarrazú",
      "Aserrí",
      "Mora",
      "Goicoechea",
      "Santa Ana",
    ],
  },
};
